Repository UMC-5th-Coumo/server, pull requests merged in 2024-02, with the labels that each got.

#32 [Feat/#30] : 인구통계별 방문 통계 조회 API 구현
  server/src/main/java/coumo/server/converter/StatisticsConverter.java
  server/src/main/java/coumo/server/repository/CustomerStoreRepository.java
  server/src/main/java/coumo/server/service/statistics/StatisticsService.java
  server/src/main/java/coumo/server/web/controller/StatisticsController.java
  server/src/main/java/coumo/server/web/dto/StatisticsResponseDTO.java
  server/src/main/java/coumo/server/web/dto/TimeResponseDTO.java
  server/src/main/java/coumo/server/web/dto/WeekResponseDTO.java
Labels: :sparkles: feature, 🐥 솔비

#31 [Refactor/#11] 동네소식 API - WEB | 페이징 처리, 커스텀 어노테이션 생성
  server/src/main/java/coumo/server/apiPayload/code/status/ErrorStatus.java
  server/src/main/java/coumo/server/apiPayload/exception/ExceptionAdvice.java
  server/src/main/java/coumo/server/converter/NoticeConverter.java
  server/src/main/java/coumo/server/repository/NoticeRepository.java
  server/src/main/java/coumo/server/service/notice/NoticeService.java
  server/src/main/java/coumo/server/service/notice/NoticeServiceImpl.java
  server/src/main/java/coumo/server/service/owner/OwnerService.java
  server/src/main/java/coumo/server/service/owner/OwnerServiceImpl.java
  server/src/main/java/coumo/server/validation/annotation/CheckPage.java
  server/src/main/java/coumo/server/validation/annotation/ExistNotice.java
  server/src/main/java/coumo/server/validation/annotation/ExistOwner.java
  server/src/main/java/coumo/server/validation/validator/CheckPageValidator.java
  server/src/main/java/coumo/server/validation/validator/ExistNoticeValidator.java
  server/src/main/java/coumo/server/validation/validator/ExistOwnerValidator.java
  server/src/main/java/coumo/server/web/controller/NoticeController.java
  server/src/main/java/coumo/server/web/dto/NoticeResponseDTO.java
Labels: 🐰 수민, :recycle: refactor

#36 [Feat/#35] : 월간분석레포트 API 구현
  server/src/main/java/coumo/server/repository/CustomerStoreRepository.java
  server/src/main/java/coumo/server/repository/StatisticsRepository.java
  server/src/main/java/coumo/server/service/statistics/StatisticsService.java
  server/src/main/java/coumo/server/web/controller/StatisticsController.java
  server/src/main/java/coumo/server/web/dto/StatisticsResponseDTO.java
Labels: :sparkles: feature, 🐥 솔비

#37 [Feat/#19] 로그인&회원가입 기능 추가(*일부 도메인 수정)
  server/build.gradle
  server/src/main/java/coumo/server/converter/CustomerConverter.java
  server/src/main/java/coumo/server/converter/OwnerConverter.java
  server/src/main/java/coumo/server/domain/Customer.java
  server/src/main/java/coumo/server/domain/Owner.java
  server/src/main/java/coumo/server/domain/enums/Gender.java
  server/src/main/java/coumo/server/jwt/AppJWTFilter.java
  server/src/main/java/coumo/server/jwt/AppLoginFilter.java
  server/src/main/java/coumo/server/jwt/JWTFilter.java
  server/src/main/java/coumo/server/jwt/JWTUtil.java
  server/src/main/java/coumo/server/jwt/SecurityConfig.java
  server/src/main/java/coumo/server/jwt/WebLoginFilter.java
  server/src/main/java/coumo/server/repository/CustomerRepository.java
  server/src/main/java/coumo/server/repository/OwnerRepository.java
  server/src/main/java/coumo/server/service/customer/CustomCustomerDetailsService.java
  server/src/main/java/coumo/server/service/customer/CustomerService.java
  server/src/main/java/coumo/server/service/customer/CustomerServiceImpl.java
  server/src/main/java/coumo/server/service/owner/CustomOwnerDetailsService.java
  server/src/main/java/coumo/server/service/owner/OwnerService.java
  server/src/main/java/coumo/server/service/owner/OwnerServiceImpl.java
  server/src/main/java/coumo/server/web/controller/CustomerRestController.java
  server/src/main/java/coumo/server/web/controller/OwnerRestController.java
  server/src/main/java/coumo/server/web/dto/CustomCustomerDetails.java
  server/src/main/java/coumo/server/web/dto/CustomOwnerDetails.java
  server/src/main/java/coumo/server/web/dto/CustomerRequestDTO.java
  server/src/main/java/coumo/server/web/dto/CustomerResponseDTO.java
  server/src/main/java/coumo/server/web/dto/OwnerRequestDTO.java
  server/src/main/java/coumo/server/web/dto/OwnerResponseDTO.java
Labels: :sparkles: feature, 🦊 정교

#51 [Fix/#50] repository 수정
  src/main/java/coumo/server/repository/CustomerStoreRepository.java
  src/main/java/coumo/server/service/statistics/StatisticsService.java
Labels: :bug: bug, 🐥 솔비

#57 [Feat/#54] ✨ AWS S3 설정
  build.gradle
  src/main/java/coumo/server/apiPayload/code/status/ErrorStatus.java
  src/main/java/coumo/server/aws/s3/AmazonS3Manager.java
  src/main/java/coumo/server/aws/s3/Filepath.java
  src/main/java/coumo/server/config/AmazonConfig.java
  src/main/java/coumo/server/domain/Menu.java
  src/main/java/coumo/server/jwt/JWTFilter.java
  src/main/java/coumo/server/service/store/StoreCommandService.java
  src/main/java/coumo/server/service/store/StoreCommandServiceImpl.java
  src/main/java/coumo/server/web/controller/StoreWebRestController.java
  src/main/resources/application-prod.yml
Labels: :sparkles: feature, 🐳 현우

#58 [Fix/#55] 가게, 지도, 메뉴 조회 버그 해결하기
  src/main/java/coumo/server/converter/StoreConverter.java
  src/main/java/coumo/server/domain/Store.java
  src/main/java/coumo/server/repository/CustomerStoreRepository.java
  src/main/java/coumo/server/repository/MenuRepository.java
  src/main/java/coumo/server/repository/OwnerCouponRepository.java
  src/main/java/coumo/server/repository/StoreImageRepository.java
  src/main/java/coumo/server/repository/StoreRepository.java
  src/main/java/coumo/server/service/store/StoreQueryService.java
  src/main/java/coumo/server/service/store/StoreQueryServiceImpl.java
  src/main/java/coumo/server/web/controller/StoreAppRestController.java
  src/main/java/coumo/server/web/controller/StoreWebRestController.java
  src/main/java/coumo/server/web/dto/StoreResponseDTO.java
Labels: :bug: bug, 🐳 현우

#59 [Feat] ✨ AWS S3 이미지 적용
  .gitignore
  build.gradle
  src/main/java/coumo/server/apiPayload/code/status/ErrorStatus.java
  src/main/java/coumo/server/aws/s3/AmazonS3Manager.java
  src/main/java/coumo/server/aws/s3/Filepath.java
  src/main/java/coumo/server/config/AmazonConfig.java
  src/main/java/coumo/server/converter/StoreConverter.java
  src/main/java/coumo/server/domain/Menu.java
  src/main/java/coumo/server/domain/Store.java
  src/main/java/coumo/server/jwt/JWTFilter.java
  src/main/java/coumo/server/repository/CustomerStoreRepository.java
  src/main/java/coumo/server/repository/MenuRepository.java
  src/main/java/coumo/server/repository/OwnerCouponRepository.java
  src/main/java/coumo/server/repository/StoreImageRepository.java
  src/main/java/coumo/server/repository/StoreRepository.java
  src/main/java/coumo/server/service/statistics/StatisticsService.java
  src/main/java/coumo/server/service/store/StoreCommandService.java
  src/main/java/coumo/server/service/store/StoreCommandServiceImpl.java
  src/main/java/coumo/server/service/store/StoreQueryService.java
  src/main/java/coumo/server/service/store/StoreQueryServiceImpl.java
  src/main/java/coumo/server/web/controller/StoreAppRestController.java
  src/main/java/coumo/server/web/controller/StoreWebRestController.java
  src/main/java/coumo/server/web/dto/StoreResponseDTO.java
  src/main/resources/application-prod.yml
Labels: :sparkles: feature, 🐳 현우

#60 [Fix/#55]: CORS, S3 코드 수정
  src/main/java/coumo/server/aws/s3/AmazonS3Manager.java
  src/main/java/coumo/server/config/WebConfig.java
Labels: :bug: bug, 🐳 현우

#67 [Fix]: :bug: CORS 수정
  src/main/java/coumo/server/config/WebConfig.java
  src/main/java/coumo/server/web/controller/RootController.java
Labels: :bug: bug, 🐳 현우

#68 [Fix]: :bug: CORS 수정
  src/main/java/coumo/server/config/WebConfig.java
  src/main/java/coumo/server/web/controller/RootController.java
Labels: :bug: bug, 🐳 현우

#70 [Fix]: :bug: CORS 수정
  src/main/java/coumo/server/config/WebConfig.java
Labels: :bug: bug, 🐳 현우

#72 [Fix]: :bug: ELB 메모리 이상 때문에 재배포 시도
  src/main/java/coumo/server/web/controller/RootController.java
Labels: :construction_worker: ci, 🐳 현우

#61 [Feat/#15] 쿠폰 API 구현 완료
  src/main/java/coumo/server/domain/OwnerCoupon.java
  src/main/java/coumo/server/repository/CustomerStoreRepository.java
  src/main/java/coumo/server/repository/OwnerCouponRepository.java
  src/main/java/coumo/server/repository/OwnerRepository.java
  src/main/java/coumo/server/service/coupon/CouponService.java
  src/main/java/coumo/server/service/coupon/CouponServiceImpl.java
  src/main/java/coumo/server/service/coupon/CustomerStoreService.java
  src/main/java/coumo/server/service/coupon/CustomerStoreServiceImpl.java
  src/main/java/coumo/server/service/coupon/OwnerCouponService.java
  src/main/java/coumo/server/service/coupon/OwnerCouponServiceImpl.java
  src/main/java/coumo/server/web/controller/CouponController.java
  src/main/java/coumo/server/web/dto/CouponRequestDTO.java
  src/main/java/coumo/server/web/dto/CouponResponseDTO.java
Labels: :sparkles: feature, 🐰 수민

#63 [Feat/#11] 동네소식 API 구현 완료
  src/main/java/coumo/server/domain/OwnerCoupon.java
  src/main/java/coumo/server/repository/CustomerStoreRepository.java
  src/main/java/coumo/server/repository/NoticeImageRepository.java
  src/main/java/coumo/server/repository/NoticeRepository.java
  src/main/java/coumo/server/repository/OwnerCouponRepository.java
  src/main/java/coumo/server/repository/OwnerRepository.java
  src/main/java/coumo/server/service/coupon/CouponService.java
  src/main/java/coumo/server/service/coupon/CouponServiceImpl.java
  src/main/java/coumo/server/service/coupon/CustomerStoreService.java
  src/main/java/coumo/server/service/coupon/CustomerStoreServiceImpl.java
  src/main/java/coumo/server/service/coupon/OwnerCouponService.java
  src/main/java/coumo/server/service/coupon/OwnerCouponServiceImpl.java
  src/main/java/coumo/server/service/notice/NoticeService.java
  src/main/java/coumo/server/service/notice/NoticeServiceImpl.java
  src/main/java/coumo/server/web/controller/CouponController.java
  src/main/java/coumo/server/web/controller/NoticeController.java
  src/main/java/coumo/server/web/dto/CouponRequestDTO.java
  src/main/java/coumo/server/web/dto/CouponResponseDTO.java
  src/main/java/coumo/server/web/dto/NoticeRequestDTO.java
  src/main/java/coumo/server/web/dto/NoticeResponseDTO.java
Labels: :sparkles: feature, 🐰 수민

#66 [Fix/#65] 변경된 기획 반영
  src/main/java/coumo/server/converter/NoticeConverter.java
  src/main/java/coumo/server/domain/OwnerCoupon.java
  src/main/java/coumo/server/domain/Store.java
  src/main/java/coumo/server/repository/CustomerStoreRepository.java
  src/main/java/coumo/server/repository/NoticeImageRepository.java
  src/main/java/coumo/server/repository/NoticeRepository.java
  src/main/java/coumo/server/repository/OwnerCouponRepository.java
  src/main/java/coumo/server/repository/StoreRepository.java
  src/main/java/coumo/server/service/notice/NoticeService.java
  src/main/java/coumo/server/service/notice/NoticeServiceImpl.java
  src/main/java/coumo/server/service/store/StoreCommandServiceImpl.java
  src/main/java/coumo/server/service/store/StoreQueryService.java
  src/main/java/coumo/server/service/store/StoreQueryServiceImpl.java
  src/main/java/coumo/server/web/controller/NoticeController.java
  src/main/java/coumo/server/web/controller/OwnerRestController.java
  src/main/java/coumo/server/web/controller/StoreAppRestController.java
  src/main/java/coumo/server/web/controller/StoreWebRestController.java
  src/main/java/coumo/server/web/dto/CouponResponseDTO.java
  src/main/java/coumo/server/web/dto/NoticeRequestDTO.java
  src/main/java/coumo/server/web/dto/NoticeResponseDTO.java
  src/main/java/coumo/server/web/dto/StoreResponseDTO.java
Labels: :ambulance: hotfix, 🐳 현우

#73 [Feat/#56] : 아이디 중복확인 & 아이디 찾기(문자메세지 인증) & 내 프로필 조회 API 구현
  build.gradle
  src/main/java/coumo/server/converter/CustomerConverter.java
  src/main/java/coumo/server/converter/OwnerConverter.java
  src/main/java/coumo/server/repository/CustomerRepository.java
  src/main/java/coumo/server/repository/OwnerRepository.java
  src/main/java/coumo/server/service/customer/CustomerService.java
  src/main/java/coumo/server/service/customer/CustomerServiceImpl.java
  src/main/java/coumo/server/service/owner/OwnerService.java
  src/main/java/coumo/server/service/owner/OwnerServiceImpl.java
  src/main/java/coumo/server/sms/MessageService.java
  src/main/java/coumo/server/sms/VerificationCodeStorage.java
  src/main/java/coumo/server/web/controller/CustomerRestController.java
  src/main/java/coumo/server/web/controller/OwnerRestController.java
  src/main/java/coumo/server/web/dto/CustomerRequestDTO.java
  src/main/java/coumo/server/web/dto/CustomerResponseDTO.java
  src/main/java/coumo/server/web/dto/LoginIdDTO.java
  src/main/java/coumo/server/web/dto/OwnerRequestDTO.java
  src/main/java/coumo/server/web/dto/OwnerResponseDTO.java
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
Labels: :sparkles: feature, 🦊 정교

#76 [CI]: 👷‍♂️ 수정 사항 배포!
  build.gradle
  src/main/java/coumo/server/converter/CustomerConverter.java
  src/main/java/coumo/server/converter/NoticeConverter.java
  src/main/java/coumo/server/converter/OwnerConverter.java
  src/main/java/coumo/server/domain/OwnerCoupon.java
  src/main/java/coumo/server/domain/Store.java
  src/main/java/coumo/server/repository/CustomerRepository.java
  src/main/java/coumo/server/repository/CustomerStoreRepository.java
  src/main/java/coumo/server/repository/NoticeImageRepository.java
  src/main/java/coumo/server/repository/NoticeRepository.java
  src/main/java/coumo/server/repository/OwnerCouponRepository.java
  src/main/java/coumo/server/repository/OwnerRepository.java
  src/main/java/coumo/server/repository/StoreRepository.java
  src/main/java/coumo/server/service/coupon/CustomerStoreServiceImpl.java
  src/main/java/coumo/server/service/customer/CustomerService.java
  src/main/java/coumo/server/service/customer/CustomerServiceImpl.java
  src/main/java/coumo/server/service/owner/OwnerService.java
  src/main/java/coumo/server/service/owner/OwnerServiceImpl.java
  src/main/java/coumo/server/service/store/StoreCommandServiceImpl.java
  src/main/java/coumo/server/service/store/StoreQueryService.java
  src/main/java/coumo/server/service/store/StoreQueryServiceImpl.java
  src/main/java/coumo/server/sms/MessageService.java
  src/main/java/coumo/server/sms/VerificationCodeStorage.java
  src/main/java/coumo/server/web/controller/CustomerRestController.java
  src/main/java/coumo/server/web/controller/OwnerRestController.java
  src/main/java/coumo/server/web/controller/StoreAppRestController.java
  src/main/java/coumo/server/web/controller/StoreWebRestController.java
  src/main/java/coumo/server/web/dto/CouponResponseDTO.java
  src/main/java/coumo/server/web/dto/CustomerRequestDTO.java
  src/main/java/coumo/server/web/dto/CustomerResponseDTO.java
  src/main/java/coumo/server/web/dto/LoginIdDTO.java
  src/main/java/coumo/server/web/dto/OwnerRequestDTO.java
  src/main/java/coumo/server/web/dto/OwnerResponseDTO.java
  src/main/java/coumo/server/web/dto/StoreResponseDTO.java
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
Labels: :construction_worker: ci, 🐳 현우

#77 Revert "[CI]: 👷‍♂️ 수정 사항 배포!"
  build.gradle
  src/main/java/coumo/server/converter/CustomerConverter.java
  src/main/java/coumo/server/converter/NoticeConverter.java
  src/main/java/coumo/server/converter/OwnerConverter.java
  src/main/java/coumo/server/domain/OwnerCoupon.java
  src/main/java/coumo/server/domain/Store.java
  src/main/java/coumo/server/repository/CustomerRepository.java
  src/main/java/coumo/server/repository/CustomerStoreRepository.java
  src/main/java/coumo/server/repository/NoticeImageRepository.java
  src/main/java/coumo/server/repository/NoticeRepository.java
  src/main/java/coumo/server/repository/OwnerCouponRepository.java
  src/main/java/coumo/server/repository/OwnerRepository.java
  src/main/java/coumo/server/repository/StoreRepository.java
  src/main/java/coumo/server/service/coupon/CustomerStoreServiceImpl.java
  src/main/java/coumo/server/service/customer/CustomerService.java
  src/main/java/coumo/server/service/customer/CustomerServiceImpl.java
  src/main/java/coumo/server/service/owner/OwnerService.java
  src/main/java/coumo/server/service/owner/OwnerServiceImpl.java
  src/main/java/coumo/server/service/store/StoreCommandServiceImpl.java
  src/main/java/coumo/server/service/store/StoreQueryService.java
  src/main/java/coumo/server/service/store/StoreQueryServiceImpl.java
  src/main/java/coumo/server/sms/MessageService.java
  src/main/java/coumo/server/sms/VerificationCodeStorage.java
  src/main/java/coumo/server/web/controller/CustomerRestController.java
  src/main/java/coumo/server/web/controller/OwnerRestController.java
  src/main/java/coumo/server/web/controller/StoreAppRestController.java
  src/main/java/coumo/server/web/controller/StoreWebRestController.java
  src/main/java/coumo/server/web/dto/CouponResponseDTO.java
  src/main/java/coumo/server/web/dto/CustomerRequestDTO.java
  src/main/java/coumo/server/web/dto/CustomerResponseDTO.java
  src/main/java/coumo/server/web/dto/LoginIdDTO.java
  src/main/java/coumo/server/web/dto/OwnerRequestDTO.java
  src/main/java/coumo/server/web/dto/OwnerResponseDTO.java
  src/main/java/coumo/server/web/dto/StoreResponseDTO.java
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
Labels: :construction_worker: ci, 🐳 현우

#78 [Fix]: :construction_worker: release 변경
  .github/workflows/dev_deploy.yml
Labels: :construction_worker: ci, 🐳 현우

#79 [Feat/#64] QR을 이용한 도장 API 구현 완료
  build.gradle
  src/main/java/coumo/server/service/qr/QRService.java
  src/main/java/coumo/server/service/qr/QRServiceImpl.java
  src/main/java/coumo/server/web/controller/QRController.java
  src/main/java/coumo/server/web/dto/QRRequestDTO.java
Labels: :sparkles: feature, 🐰 수민

#82 [Feat/#75] : 회원가입 시 휴대폰 인증 API 구현 및 기능 추가 WEB&APP
  src/main/java/coumo/server/converter/OwnerConverter.java
  src/main/java/coumo/server/web/controller/CustomerRestController.java
  src/main/java/coumo/server/web/controller/OwnerRestController.java
  src/main/java/coumo/server/web/dto/CustomerVerificationSuccessResponse.java
  src/main/java/coumo/server/web/dto/OwnerResponseDTO.java
  src/main/java/coumo/server/web/dto/VerificationResponseDTO.java
  src/main/java/coumo/server/web/dto/VerificationSuccessResponse.java
Labels: :sparkles: feature, 🦊 정교

#83 [Feat/#64] QR 생성 API POST->GET
  src/main/java/coumo/server/web/controller/QRController.java
Labels: :sparkles: feature, 🐰 수민

#84 [CI]: 👷‍♂️ PULL REQUEST 머지
  src/main/java/coumo/server/converter/OwnerConverter.java
  src/main/java/coumo/server/service/statistics/StatisticsService.java
  src/main/java/coumo/server/web/controller/CustomerRestController.java
  src/main/java/coumo/server/web/controller/OwnerRestController.java
  src/main/java/coumo/server/web/controller/QRController.java
  src/main/java/coumo/server/web/dto/CustomerVerificationSuccessResponse.java
  src/main/java/coumo/server/web/dto/OwnerResponseDTO.java
  src/main/java/coumo/server/web/dto/StatisticsResponseDTO.java
  src/main/java/coumo/server/web/dto/VerificationResponseDTO.java
  src/main/java/coumo/server/web/dto/VerificationSuccessResponse.java
  src/main/resources/application-prod.yml
Labels: :construction_worker: ci, 🐳 현우

#87 [Fix/#86] : 로그인, 인증번호 관련 코드 수정 WEB&APP
  src/main/java/coumo/server/converter/CustomerConverter.java
  src/main/java/coumo/server/converter/OwnerConverter.java
  src/main/java/coumo/server/web/controller/CustomerRestController.java
  src/main/java/coumo/server/web/controller/OwnerRestController.java
  src/main/java/coumo/server/web/dto/CustomerRequestDTO.java
  src/main/java/coumo/server/web/dto/OwnerRequestDTO.java
  src/main/java/coumo/server/web/dto/OwnerResponseDTO.java
Labels: 🦊 정교, :recycle: refactor

#94 [CI] 👷‍♂️ ELB에 배포하기
  src/main/java/coumo/server/converter/CustomerConverter.java
  src/main/java/coumo/server/converter/OwnerConverter.java
  src/main/java/coumo/server/web/controller/CustomerRestController.java
  src/main/java/coumo/server/web/controller/OwnerRestController.java
  src/main/java/coumo/server/web/dto/CustomerRequestDTO.java
  src/main/java/coumo/server/web/dto/OwnerRequestDTO.java
  src/main/java/coumo/server/web/dto/OwnerResponseDTO.java
Labels: :construction_worker: ci, 🐳 현우

#89 [Fix/#88] : 휴무일처리
  src/main/java/coumo/server/domain/Timetable.java
  src/main/java/coumo/server/service/statistics/StatisticsService.java
  src/main/java/coumo/server/web/dto/StatisticsResponseDTO.java
Labels: :bug: bug, 🐥 솔비

#96 [Fix/#85] 내 쿠폰 최신순/많이모은순 API 오류 해결 (feat. QueryDSL)
  build.gradle
  src/main/generated/coumo/server/domain/QCustomer.java
  src/main/generated/coumo/server/domain/QDesignReceipt.java
  src/main/generated/coumo/server/domain/QMenu.java
  src/main/generated/coumo/server/domain/QNotice.java
  src/main/generated/coumo/server/domain/QNoticeImage.java
  src/main/generated/coumo/server/domain/QOwner.java
  src/main/generated/coumo/server/domain/QOwnerCoupon.java
  src/main/generated/coumo/server/domain/QStore.java
  src/main/generated/coumo/server/domain/QStoreImage.java
  src/main/generated/coumo/server/domain/QSubscriptionReceipt.java
  src/main/generated/coumo/server/domain/QTimetable.java
  src/main/generated/coumo/server/domain/common/QBaseEntity.java
  src/main/generated/coumo/server/domain/mapping/QCustomerStore.java
  src/main/java/coumo/server/config/QueryDSLConfig.java
  src/main/java/coumo/server/repository/CustomerStoreQueryRepository.java
  src/main/java/coumo/server/repository/CustomerStoreQueryRepositoryImpl.java
  src/main/java/coumo/server/repository/CustomerStoreRepository.java
  src/main/java/coumo/server/service/coupon/CustomerStoreServiceImpl.java
  src/main/java/coumo/server/web/controller/CouponController.java
  src/main/java/coumo/server/web/controller/NoticeController.java
  src/main/java/coumo/server/web/controller/QRController.java
  src/main/java/coumo/server/web/dto/CouponResponseDTO.java
Labels: :bug: bug, 🐰 수민

#99 [Feat/#95] 커스텀 쿠폰 UI 서비스 기능 구현 및 일부코드 수정 WEB
  src/main/java/coumo/server/converter/DesignReceiptConverter.java
  src/main/java/coumo/server/domain/DesignReceipt.java
  src/main/java/coumo/server/domain/Owner.java
  src/main/java/coumo/server/repository/DesignReceiptRepository.java
  src/main/java/coumo/server/repository/StoreRepository.java
  src/main/java/coumo/server/service/design/DesignReceiptService.java
  src/main/java/coumo/server/service/design/DesignReceiptServiceImpl.java
  src/main/java/coumo/server/web/controller/CustomerRestController.java
  src/main/java/coumo/server/web/controller/DesignReceiptController.java
  src/main/java/coumo/server/web/dto/CustomerRequestDTO.java
  src/main/java/coumo/server/web/dto/DesignReceiptRequestDTO.java
  src/main/java/coumo/server/web/dto/DesignReceiptResponseDTO.java
  src/main/java/coumo/server/web/dto/VerificationAppPwSuccessResponse.java
Labels: :sparkles: feature, 🦊 정교

#102 [Fix/#101] S3 CORS으로 인한 Http 메소드 수정 및 가게 상세 주소 추가
  src/main/java/coumo/server/converter/StoreConverter.java
  src/main/java/coumo/server/domain/Store.java
  src/main/java/coumo/server/service/store/StoreCommandServiceImpl.java
  src/main/java/coumo/server/web/controller/StoreWebRestController.java
  src/main/java/coumo/server/web/dto/StoreRequestDTO.java
  src/main/java/coumo/server/web/dto/StoreResponseDTO.java
Labels: :ambulance: hotfix, 🐳 현우

#107 [CI] 👷 ELB 배표하기
  src/main/java/coumo/server/converter/DesignReceiptConverter.java
  src/main/java/coumo/server/converter/StoreConverter.java
  src/main/java/coumo/server/domain/DesignReceipt.java
  src/main/java/coumo/server/domain/Owner.java
  src/main/java/coumo/server/domain/Store.java
  src/main/java/coumo/server/repository/DesignReceiptRepository.java
  src/main/java/coumo/server/repository/StoreRepository.java
  src/main/java/coumo/server/service/design/DesignReceiptService.java
  src/main/java/coumo/server/service/design/DesignReceiptServiceImpl.java
  src/main/java/coumo/server/service/store/StoreCommandServiceImpl.java
  src/main/java/coumo/server/web/controller/CustomerRestController.java
  src/main/java/coumo/server/web/controller/DesignReceiptController.java
  src/main/java/coumo/server/web/controller/StoreWebRestController.java
  src/main/java/coumo/server/web/dto/CustomerRequestDTO.java
  src/main/java/coumo/server/web/dto/DesignReceiptRequestDTO.java
  src/main/java/coumo/server/web/dto/DesignReceiptResponseDTO.java
  src/main/java/coumo/server/web/dto/StoreRequestDTO.java
  src/main/java/coumo/server/web/dto/StoreResponseDTO.java
  src/main/java/coumo/server/web/dto/VerificationAppPwSuccessResponse.java
Labels: :construction_worker: ci, 🐳 현우

#108 [Fix/#85] 동네소식 API 오류 해결 완료
  src/main/generated/coumo/server/domain/QNotice.java
  src/main/java/coumo/server/domain/Notice.java
  src/main/java/coumo/server/domain/NoticeImage.java
  src/main/java/coumo/server/repository/NoticeImageRepository.java
  src/main/java/coumo/server/repository/NoticeRepository.java
  src/main/java/coumo/server/repository/StoreRepository.java
  src/main/java/coumo/server/service/notice/NoticeService.java
  src/main/java/coumo/server/service/notice/NoticeServiceImpl.java
  src/main/java/coumo/server/web/controller/NoticeController.java
  src/main/java/coumo/server/web/dto/NoticeResponseDTO.java
Labels: :bug: bug, 🐰 수민

#109 [Fix/#85] 동네소식 API 오류 해결 완료
  src/main/generated/coumo/server/domain/QNotice.java
  src/main/java/coumo/server/domain/Notice.java
  src/main/java/coumo/server/domain/NoticeImage.java
  src/main/java/coumo/server/repository/NoticeImageRepository.java
  src/main/java/coumo/server/repository/NoticeRepository.java
  src/main/java/coumo/server/repository/StoreRepository.java
  src/main/java/coumo/server/service/notice/NoticeService.java
  src/main/java/coumo/server/service/notice/NoticeServiceImpl.java
  src/main/java/coumo/server/web/controller/NoticeController.java
  src/main/java/coumo/server/web/dto/NoticeResponseDTO.java
Labels: :bug: bug, 🐰 수민

#110 [Fix/#85] 동네소식 오타
  src/main/generated/coumo/server/domain/QNotice.java
  src/main/java/coumo/server/service/notice/NoticeServiceImpl.java
Labels: :ambulance: hotfix, 🐰 수민

#111 [HOTFIX] 동네소식 오타
  src/main/generated/coumo/server/domain/QNotice.java
  src/main/java/coumo/server/service/notice/NoticeServiceImpl.java
Labels: :ambulance: hotfix, 🐰 수민

#104 [Feat/#103] ✨ 대표 쿠폰 조회API & 도장 이미지를 url로 변경하여 앱으로 응답
  src/main/java/coumo/server/converter/MainCouponConverter.java
  src/main/java/coumo/server/service/coupon/OwnerCouponServiceImpl.java
  src/main/java/coumo/server/service/store/StoreQueryServiceImpl.java
  src/main/java/coumo/server/util/StampURL.java
  src/main/java/coumo/server/web/controller/MyCouponRestController.java
  src/main/java/coumo/server/web/dto/CouponResponseDTO.java
Labels: :sparkles: feature, 🐳 현우

#113 [CI] 👷‍♂️ ELB 배포
  src/main/java/coumo/server/converter/MainCouponConverter.java
  src/main/java/coumo/server/service/coupon/OwnerCouponServiceImpl.java
  src/main/java/coumo/server/service/store/StoreQueryServiceImpl.java
  src/main/java/coumo/server/util/StampURL.java
  src/main/java/coumo/server/web/controller/MyCouponRestController.java
  src/main/java/coumo/server/web/dto/CouponResponseDTO.java
Labels: :construction_worker: ci, 🐳 현우

#115 [Fix/#103]: 기획 변경된 응답 수정
  src/main/java/coumo/server/domain/enums/StampMax.java
  src/main/java/coumo/server/service/store/StoreQueryServiceImpl.java
  src/main/java/coumo/server/web/dto/StoreResponseDTO.java
Labels: :ambulance: hotfix, 🐳 현우

#116 [Fix/#112] 쿠폰 관련 API 오류 수정
  src/main/generated/coumo/server/domain/QDesignReceipt.java
  src/main/generated/coumo/server/domain/QNotice.java
  src/main/generated/coumo/server/domain/QOwner.java
  src/main/generated/coumo/server/domain/QStore.java
  src/main/java/coumo/server/domain/enums/StampMax.java
  src/main/java/coumo/server/domain/mapping/CustomerStore.java
  src/main/java/coumo/server/repository/CustomerStoreQueryRepositoryImpl.java
  src/main/java/coumo/server/repository/NoticeImageRepository.java
  src/main/java/coumo/server/service/notice/NoticeServiceImpl.java
  src/main/java/coumo/server/service/qr/QRService.java
  src/main/java/coumo/server/service/qr/QRServiceImpl.java
  src/main/java/coumo/server/web/controller/CouponController.java
  src/main/java/coumo/server/web/controller/NoticeController.java
  src/main/java/coumo/server/web/controller/QRController.java
  src/main/java/coumo/server/web/dto/CouponResponseDTO.java
  src/main/java/coumo/server/web/dto/NoticeResponseDTO.java
Labels: :bug: bug, 🐰 수민

#117 [Fix] 쿠폰 API 관련 오류 해결
  src/main/generated/coumo/server/domain/QDesignReceipt.java
  src/main/generated/coumo/server/domain/QNotice.java
  src/main/generated/coumo/server/domain/QOwner.java
  src/main/generated/coumo/server/domain/QStore.java
  src/main/java/coumo/server/domain/enums/StampMax.java
  src/main/java/coumo/server/domain/mapping/CustomerStore.java
  src/main/java/coumo/server/repository/CustomerStoreQueryRepositoryImpl.java
  src/main/java/coumo/server/repository/NoticeImageRepository.java
  src/main/java/coumo/server/service/notice/NoticeServiceImpl.java
  src/main/java/coumo/server/service/qr/QRService.java
  src/main/java/coumo/server/service/qr/QRServiceImpl.java
  src/main/java/coumo/server/web/controller/CouponController.java
  src/main/java/coumo/server/web/controller/NoticeController.java
  src/main/java/coumo/server/web/controller/QRController.java
  src/main/java/coumo/server/web/dto/CouponResponseDTO.java
  src/main/java/coumo/server/web/dto/NoticeResponseDTO.java
Labels: :bug: bug, 🐰 수민

#118 [Fix/#103]: 여러 개 조회 응급처치
  src/main/java/coumo/server/service/coupon/OwnerCouponServiceImpl.java
Labels: :ambulance: hotfix, 🐳 현우

#119 [Fix/#103]: 여러 개 조회 응급처치
  src/main/java/coumo/server/apiPayload/code/status/ErrorStatus.java
  src/main/java/coumo/server/web/controller/MyCouponRestController.java
Labels: :ambulance: hotfix, 🐳 현우

#124 [Fix/#123]: ♻️ [아이디 찾기] 로그인ID 반환 오류 수정, 일부 코드 수정
  src/main/java/coumo/server/repository/CustomerRepository.java
  src/main/java/coumo/server/service/customer/CustomerService.java
  src/main/java/coumo/server/service/customer/CustomerServiceImpl.java
  src/main/java/coumo/server/web/controller/CustomerRestController.java
  src/main/java/coumo/server/web/controller/OwnerRestController.java
  src/main/java/coumo/server/web/dto/LoginAppIdDTO.java
  src/main/java/coumo/server/web/dto/VerificationAppResponseDTO.java
Labels: :recycle: refactor

#125 [CI]: 👷‍♂️ ELB 배포
  src/main/java/coumo/server/domain/OwnerCoupon.java
  src/main/java/coumo/server/repository/CustomerRepository.java
  src/main/java/coumo/server/service/coupon/CouponServiceImpl.java
  src/main/java/coumo/server/service/customer/CustomerService.java
  src/main/java/coumo/server/service/customer/CustomerServiceImpl.java
  src/main/java/coumo/server/web/controller/CouponController.java
  src/main/java/coumo/server/web/controller/CustomerRestController.java
  src/main/java/coumo/server/web/controller/OwnerRestController.java
  src/main/java/coumo/server/web/dto/CouponResponseDTO.java
  src/main/java/coumo/server/web/dto/LoginAppIdDTO.java
  src/main/java/coumo/server/web/dto/VerificationAppResponseDTO.java
Labels: :construction_worker: ci, 🐳 현우

#126 [CI] 👷‍♂️ ELB 배포
  src/main/java/coumo/server/web/controller/StoreAppRestController.java
Labels: :construction_worker: ci, 🐳 현우

#127 [Fix]: 글 시간 버그 수정
  src/main/java/coumo/server/converter/NoticeConverter.java
Labels: :ambulance: hotfix, 🐳 현우

#106 [Feat/#105]: :sparkles: 토큰 검증
  src/main/java/coumo/server/repository/OwnerRepository.java
  src/main/java/coumo/server/service/owner/OwnerService.java
  src/main/java/coumo/server/service/owner/OwnerServiceImpl.java
  src/main/java/coumo/server/util/TokenCheck.java
  src/main/java/coumo/server/web/controller/StoreWebRestController.java
Labels: :sparkles: feature, 🐳 현우

#132 [Fix/#105]: 토큰 검증 오류 검증 주석
  src/main/java/coumo/server/web/controller/StoreWebRestController.java
Labels: :ambulance: hotfix, 🐳 현우

#134 [Fix/#120] 동네소식 API 오류 수정
  src/main/java/coumo/server/service/notice/NoticeService.java
  src/main/java/coumo/server/service/notice/NoticeServiceImpl.java
  src/main/java/coumo/server/web/controller/NoticeController.java
Labels: :bug: bug, 🐰 수민

#135 [Fix] 동네소식 API 오류 수정
  src/main/java/coumo/server/service/notice/NoticeService.java
  src/main/java/coumo/server/service/notice/NoticeServiceImpl.java
  src/main/java/coumo/server/web/controller/NoticeController.java
Labels: :bug: bug, 🐰 수민

#133 [Fix/#100] : 토큰 검증 추가
  src/main/java/coumo/server/service/statistics/StatisticsService.java
  src/main/java/coumo/server/web/controller/StatisticsController.java
Labels: :bug: bug, 🐥 솔비

#139 [CI] : 👷‍♂️ ELB 배포
  src/main/java/coumo/server/service/statistics/StatisticsService.java
  src/main/java/coumo/server/web/controller/StatisticsController.java
Labels: :construction_worker: ci, 🐳 현우

#142 [Fix/#141] : null->none
  src/main/java/coumo/server/service/statistics/StatisticsService.java
Labels: :bug: bug, 🐥 솔비

#143 [CI] 👷‍♂️ ELB 배포
  src/main/java/coumo/server/service/statistics/StatisticsService.java
Labels: :construction_worker: ci, 🐳 현우

#145 [Fix/#120] 사장님 게시물 보기 list 오류 수정
  src/main/java/coumo/server/repository/NoticeRepository.java
  src/main/java/coumo/server/service/notice/NoticeService.java
  src/main/java/coumo/server/service/notice/NoticeServiceImpl.java
  src/main/java/coumo/server/service/store/StoreQueryService.java
  src/main/java/coumo/server/service/store/StoreQueryServiceImpl.java
  src/main/java/coumo/server/web/controller/NoticeController.java
Labels: :bug: bug, 🐰 수민

#148 [CI]: 👷‍♂️ ELB 배포
  src/main/java/coumo/server/converter/DesignReceiptConverter.java
  src/main/java/coumo/server/domain/DesignReceipt.java
  src/main/java/coumo/server/domain/enums/ReceiptState.java
  src/main/java/coumo/server/repository/DesignReceiptRepository.java
  src/main/java/coumo/server/service/design/DesignReceiptService.java
  src/main/java/coumo/server/service/design/DesignReceiptServiceImpl.java
  src/main/java/coumo/server/web/controller/DesignReceiptController.java
  src/main/java/coumo/server/web/dto/DesignReceiptServiceResponseDTO.java
  src/main/java/coumo/server/web/dto/DesignReceiptStateChangeRequestDTO.java
Labels: :construction_worker: ci, 🐳 현우

#152 [C] : 👷‍♂️ ELB 배포
  src/main/java/coumo/server/web/controller/StatisticsController.java
Labels: :construction_worker: ci, 🐳 현우

#153 [CI] : ELB 배포
  src/main/java/coumo/server/domain/Store.java
Labels: :construction_worker: ci, 🐳 현우

#154 [Fix] : 버그 수정
  src/main/java/coumo/server/domain/Store.java
Labels: :ambulance: hotfix, :construction_worker: ci, 🐳 현우

#155 [Fix/#120] 동네소식 조회 오류 수정
  src/main/java/coumo/server/repository/NoticeImageRepository.java
  src/main/java/coumo/server/service/notice/NoticeServiceImpl.java
Labels: :bug: bug, 🐰 수민

#156 [Fix/#120] 동네소식 조회 오류 수정
  src/main/java/coumo/server/repository/NoticeImageRepository.java
  src/main/java/coumo/server/service/notice/NoticeServiceImpl.java
Labels: :bug: bug, 🐰 수민

#158 [Fix/#120] 동네소식 API storeId 추가
  src/main/java/coumo/server/service/notice/NoticeServiceImpl.java
  src/main/java/coumo/server/web/dto/NoticeResponseDTO.java
Labels: 🐰 수민, :recycle: refactor

#159 [Fix/#120] 동네소식 API storeId 추가
  src/main/java/coumo/server/service/notice/NoticeServiceImpl.java
  src/main/java/coumo/server/web/dto/NoticeResponseDTO.java
Labels: 🐰 수민, :recycle: refactor

#160 [Fix/#157] API 오류 수정
  src/main/java/coumo/server/web/controller/DesignReceiptController.java
Labels: :bug: bug, 🦊 정교

#162 [CI] 👷‍♂️ ELB 배포
  src/main/java/coumo/server/config/WebConfig.java
  src/main/java/coumo/server/web/controller/DesignReceiptController.java
Labels: :construction_worker: ci, 🐳 현우

#164 [Fix/#120] StampMax
  src/main/java/coumo/server/service/qr/QRServiceImpl.java
Labels: 🐰 수민, :recycle: refactor
