Repository UMC-5th-Coumo/server, pull requests merged in 2024-01, with the labels that each got.

#4 Setting/#3] 프로젝트 세팅
  server/build.gradle
  server/src/main/java/coumo/server/apiPayload/ApiResponse.java
  server/src/main/java/coumo/server/apiPayload/code/BaseCode.java
  server/src/main/java/coumo/server/apiPayload/code/BaseErrorCode.java
  server/src/main/java/coumo/server/apiPayload/code/ErrorReasonDTO.java
  server/src/main/java/coumo/server/apiPayload/code/ReasonDTO.java
  server/src/main/java/coumo/server/apiPayload/code/status/ErrorStatus.java
  server/src/main/java/coumo/server/apiPayload/code/status/SuccessStatus.java
  server/src/main/java/coumo/server/apiPayload/exception/ExceptionAdvice.java
  server/src/main/java/coumo/server/apiPayload/exception/GeneralException.java
  server/src/main/java/coumo/server/config/SwaggerConfig.java
Labels: 🐳 현우

#8 [Feat/#7]: 프로젝트 도메인 수정
  server/.gitignore
  server/build.gradle
  server/src/main/java/coumo/server/ServerApplication.java
  server/src/main/java/coumo/server/apiPayload/ApiResponse.java
  server/src/main/java/coumo/server/apiPayload/code/BaseCode.java
  server/src/main/java/coumo/server/apiPayload/code/BaseErrorCode.java
  server/src/main/java/coumo/server/apiPayload/code/ErrorReasonDTO.java
  server/src/main/java/coumo/server/apiPayload/code/ReasonDTO.java
  server/src/main/java/coumo/server/apiPayload/code/status/ErrorStatus.java
  server/src/main/java/coumo/server/apiPayload/code/status/SuccessStatus.java
  server/src/main/java/coumo/server/apiPayload/exception/ExceptionAdvice.java
  server/src/main/java/coumo/server/apiPayload/exception/GeneralException.java
  server/src/main/java/coumo/server/config/SwaggerConfig.java
  server/src/main/java/coumo/server/domain/Customer.java
  server/src/main/java/coumo/server/domain/DesignReceipt.java
  server/src/main/java/coumo/server/domain/Menu.java
  server/src/main/java/coumo/server/domain/Notice.java
  server/src/main/java/coumo/server/domain/Owner.java
  server/src/main/java/coumo/server/domain/OwnerCoupon.java
  server/src/main/java/coumo/server/domain/Store.java
  server/src/main/java/coumo/server/domain/StoreImage.java
  server/src/main/java/coumo/server/domain/SubscriptionReceipt.java
  server/src/main/java/coumo/server/domain/Timetable.java
  server/src/main/java/coumo/server/domain/common/BaseEntity.java
  server/src/main/java/coumo/server/domain/enums/Gender.java
  server/src/main/java/coumo/server/domain/enums/NoticeType.java
  server/src/main/java/coumo/server/domain/enums/StampMax.java
  server/src/main/java/coumo/server/domain/enums/State.java
  server/src/main/java/coumo/server/domain/enums/StoreType.java
  server/src/main/java/coumo/server/domain/enums/SubscriptionType.java
  server/src/main/java/coumo/server/domain/mapping/CustomerStore.java
  server/src/main/resources/application.properties
Labels: :sparkles: feature, 🦊 정교

#13 [Feat/#12] : 전체 고객 데이터 조회 API
  server/build.gradle
  server/src/main/java/coumo/server/converter/StatisticsConverter.java
  server/src/main/java/coumo/server/repository/CustomerStoreRepository.java
  server/src/main/java/coumo/server/repository/StatisticsRepository.java
  server/src/main/java/coumo/server/service/StatisticsService.java
  server/src/main/java/coumo/server/web/controller/StatisticsController.java
  server/src/main/java/coumo/server/web/dto/CustomerDTO.java
Labels: :sparkles: feature, 🐥 솔비

#14 [Feat#10] 가게 API 구현 - WEB
  .gitignore
  server/build.gradle
  server/src/main/java/coumo/server/apiPayload/code/status/ErrorStatus.java
  server/src/main/java/coumo/server/apiPayload/exception/ExceptionAdvice.java
  server/src/main/java/coumo/server/apiPayload/exception/handler/StoreHandler.java
  server/src/main/java/coumo/server/converter/StoreConverter.java
  server/src/main/java/coumo/server/domain/Menu.java
  server/src/main/java/coumo/server/domain/Notice.java
  server/src/main/java/coumo/server/domain/Owner.java
  server/src/main/java/coumo/server/domain/Store.java
  server/src/main/java/coumo/server/domain/StoreImage.java
  server/src/main/java/coumo/server/domain/Timetable.java
  server/src/main/java/coumo/server/domain/enums/StoreType.java
  server/src/main/java/coumo/server/repository/MenuRepository.java
  server/src/main/java/coumo/server/repository/OwnerRepository.java
  server/src/main/java/coumo/server/repository/StoreImageRepository.java
  server/src/main/java/coumo/server/repository/StoreRepository.java
  server/src/main/java/coumo/server/repository/TimetableRepository.java
  server/src/main/java/coumo/server/service/store/StoreCommandService.java
  server/src/main/java/coumo/server/service/store/StoreCommandServiceImpl.java
  server/src/main/java/coumo/server/service/store/StoreQueryService.java
  server/src/main/java/coumo/server/service/store/StoreQueryServiceImpl.java
  server/src/main/java/coumo/server/web/controller/StoreAppRestController.java
  server/src/main/java/coumo/server/web/controller/StoreWebRestController.java
  server/src/main/java/coumo/server/web/dto/StoreRequestDTO.java
  server/src/main/java/coumo/server/web/dto/StoreResponseDTO.java
Labels: :sparkles: feature, 🐳 현우

#22 [ Refactor/#21] 도메인 수정
  server/src/main/java/coumo/server/domain/Customer.java
  server/src/main/java/coumo/server/domain/DesignReceipt.java
  server/src/main/java/coumo/server/domain/Menu.java
  server/src/main/java/coumo/server/domain/Notice.java
  server/src/main/java/coumo/server/domain/Owner.java
  server/src/main/java/coumo/server/domain/OwnerCoupon.java
  server/src/main/java/coumo/server/domain/Store.java
  server/src/main/java/coumo/server/domain/StoreImage.java
  server/src/main/java/coumo/server/domain/SubscriptionReceipt.java
  server/src/main/java/coumo/server/domain/Timetable.java
  server/src/main/java/coumo/server/domain/mapping/CustomerStore.java
Labels: 🐰 수민, :recycle: refactor

#25 [Refactor/#24]: 메뉴 isNew 컬럼 추가 및 반영
  server/src/main/java/coumo/server/converter/StoreConverter.java
  server/src/main/java/coumo/server/domain/Menu.java
  server/src/main/java/coumo/server/domain/enums/StoreType.java
  server/src/main/java/coumo/server/service/store/StoreCommandServiceImpl.java
  server/src/main/java/coumo/server/web/controller/StoreAppRestController.java
  server/src/main/java/coumo/server/web/dto/StoreRequestDTO.java
  server/src/main/java/coumo/server/web/dto/StoreResponseDTO.java
Labels: 🐳 현우, :recycle: refactor

#20 [Feat/#11] 동네소식 API 구현
  server/src/main/java/coumo/server/repository/NoticeRepository.java
  server/src/main/java/coumo/server/repository/OwnerRepository.java
  server/src/main/java/coumo/server/service/notice/NoticeService.java
  server/src/main/java/coumo/server/service/notice/NoticeServiceImpl.java
  server/src/main/java/coumo/server/service/owner/OwnerService.java
  server/src/main/java/coumo/server/service/owner/OwnerServiceImpl.java
  server/src/main/java/coumo/server/web/controller/NoticeController.java
  server/src/main/java/coumo/server/web/dto/NoticeRequestDTO.java
  server/src/main/java/coumo/server/web/dto/NoticeResponseDTO.java
Labels: :sparkles: feature, 🐰 수민

#29 [Fix] 게시글 저장 반환 타입 Notice로 변경
  server/src/main/java/coumo/server/repository/NoticeRepository.java
  server/src/main/java/coumo/server/service/notice/NoticeService.java
  server/src/main/java/coumo/server/service/notice/NoticeServiceImpl.java
  server/src/main/java/coumo/server/web/controller/NoticeController.java
Labels: :bug: bug

#26 [Feat/#23] : 요일별/시간대별 방문 통계 조회 API 구현
  server/src/main/java/coumo/server/converter/StatisticsConverter.java
  server/src/main/java/coumo/server/repository/CustomerStoreRepository.java
  server/src/main/java/coumo/server/repository/StatisticsRepository.java
  server/src/main/java/coumo/server/repository/TimetableRepository.java
  server/src/main/java/coumo/server/service/statistics/StatisticsService.java
  server/src/main/java/coumo/server/web/controller/StatisticsController.java
  server/src/main/java/coumo/server/web/dto/CustomerResponseDTO.java
  server/src/main/java/coumo/server/web/dto/TimeResponseDTO.java
  server/src/main/java/coumo/server/web/dto/WeekResponseDTO.java
Labels: :sparkles: feature, 🐥 솔비

#28 [Refactor/#27] 게시글 이미지 테이블 생성
  server/src/main/java/coumo/server/domain/Notice.java
  server/src/main/java/coumo/server/domain/NoticeImage.java
Labels: 🐰 수민, :recycle: refactor
